export const CLINICAL_EXPORT_COPY = {
  title: 'Resumo para consulta médica',
  subtitle: 'AiyraCare — histórico consolidado do paciente',
  printButton: 'Imprimir / salvar PDF',
  closeButton: 'Fechar',
  previewTitle: 'Pré-visualização do resumo',
  sectionAlerts: 'Alertas',
  sectionPendencies: 'Pendências',
  sectionFollowUp: 'Em acompanhamento',
  sectionPlans: 'Planos de saúde',
  sectionTimeline: 'Eventos recentes',
  sectionSummary: 'Resumo',
  footerDisclaimer:
    'Documento gerado automaticamente a partir dos registros do cuidador. Não substitui prontuário oficial do serviço de saúde. Revise com o paciente antes da consulta.',
  generatedAt: 'Gerado em',
  noPendencies: 'Sem pendências registradas.',
  noFollowUp: 'Sem acompanhamentos ativos.',
  noTimeline: 'Sem eventos recentes no período.',
  noPlans: 'Sem planos ativos registrados.',
  shareButton: 'Compartilhar link',
  shareCopied: 'Link copiado',
  shareTitle: 'Link temporário para o médico',
  consultVisitTitle: 'Levar na consulta',
  consultVisitSubtitle: 'Compartilhe um resumo com o médico — link válido por 48 horas.',
  consultVisitModeSummary: 'Para consulta',
  consultVisitModeSummaryHint: 'Alertas, medicamentos, eventos recentes — recomendado',
  consultVisitModeFull: 'Completo',
  consultVisitModeFullHint: 'Inclui exames, laudos e autorizações',
  consultVisitCopyLink: 'Copiar link',
  consultVisitShowQr: 'QR Code para o médico',
  consultVisitPrint: 'Salvar PDF / imprimir',
  consultVisitWhatsapp: 'Enviar no WhatsApp',
  consultVisitExpires: 'Válido até',
  consultVisitPreview: 'Ver pré-visualização completa',
  consultVisitQrHint: 'O médico escaneia na recepção — abre no celular sem instalar app.',
  consultVisitWhatsappHint: 'Abre o WhatsApp com o link pronto para enviar.',
  consultVisitEmailTitle: 'Enviar por e-mail ao médico',
  consultVisitEmailLabel: 'E-mail do médico',
  consultVisitDoctorNameLabel: 'Nome do médico (opcional)',
  consultVisitEmailSend: 'Enviar e-mail',
  consultVisitEmailSent: 'E-mail enviado ao médico',
  consultVisitEmailQueued: 'Link preparado — e-mail será enviado em breve',
  consultVisitReferralHint:
    'O link inclui seu código de indicação AiyraCare — ajuda a reconhecer quem compartilhou.',
  consultVisitReferralCode: 'Seu código:',
  exportFullTitle: 'Prontuário completo para consulta',
  sectionAllergies: 'Alergias',
  sectionMedications: 'Medicamentos',
  sectionVaccines: 'Vacinas',
  sectionDiagnoses: 'Diagnósticos',
  sectionDocuments: 'Arquivos',
  sectionAuthorizations: 'Autorizações',
  sectionMedicalRecords: 'Consultas e utilização',
  sectionExams: 'Exames',
  clinicianPortalTitle: 'Portal do médico',
  clinicianPortalSubtitle: 'Resumo compartilhado pelo cuidador para apoiar a consulta',
  clinicianPortalDisclaimer:
    'Documento gerado automaticamente a partir dos registros do cuidador. Não substitui prontuário oficial. Revise com o paciente ou responsável.',
  clinicianPortalModeSummary: 'Resumo para consulta',
  clinicianPortalModeFull: 'Prontuário completo',
  clinicianPortalCtaTitle: 'AiyraCare para consultórios',
  clinicianPortalCtaBody: 'Receba resumos estruturados dos seus pacientes — sem instalar app no consultório.',
  clinicianPortalCtaButton: 'Conhecer o AiyraCare',
  clinicianFeedbackPrompt: 'Este resumo foi útil para a consulta?',
  clinicianFeedbackYes: 'Sim, ajudou',
  clinicianFeedbackNo: 'Pouco útil',
  clinicianFeedbackThanks: 'Obrigado pelo retorno.',
}
